# http://docs.travis-ci.com/user/languages/r/
language: r

cache: packages

r:
  - release
  - devel

addons:
  apt:
    packages:
      - unixodbc-dev

r_check_revdep: false

after_success:

notifications:
  email:
    - zozlak@zozlak.org