# http://docs.travis-ci.com/user/languages/r/
language: r
cache: packages
sudo: required

r:
  - release
  - devel

apt_packages:
  - unixodbc-dev

r_check_revdep: false

after_success:

notifications:
  email:
    - zozlak@zozlak.org